openapi: 3.0.3
info:
  title: Todo Chatbot Backend API
  description: Phase V Todo Chatbot - FastAPI Backend
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local development
  - url: https://api.todo-chatbot.example.com
    description: Production

paths:
  /api/chat:
    post:
      summary: Process natural language chat command
      operationId: processChat
      tags: [Chat]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Chat response with action result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

  /api/tasks:
    get:
      summary: List tasks with filtering and sorting
      operationId: listTasks
      tags: [Tasks]
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, completed]
        - name: priority
          in: query
          schema:
            type: string
            enum: [High, Medium, Low]
        - name: tags
          in: query
          schema:
            type: array
            items:
              type: string
        - name: due_before
          in: query
          schema:
            type: string
            format: date-time
        - name: due_after
          in: query
          schema:
            type: string
            format: date-time
        - name: search
          in: query
          schema:
            type: string
          description: Full-text search in title and description
        - name: sort_by
          in: query
          schema:
            type: string
            enum: [created_at, due_at, priority]
            default: created_at
        - name: sort_order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskListResponse'

    post:
      summary: Create a new task
      operationId: createTask
      tags: [Tasks]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Validation error

  /api/tasks/{task_id}:
    get:
      summary: Get a specific task
      operationId: getTask
      tags: [Tasks]
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found

    put:
      summary: Update a task
      operationId: updateTask
      tags: [Tasks]
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found

    delete:
      summary: Delete a task
      operationId: deleteTask
      tags: [Tasks]
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted
        '404':
          description: Task not found

  /api/tasks/{task_id}/complete:
    post:
      summary: Mark task as complete
      operationId: completeTask
      tags: [Tasks]
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Task already completed
        '404':
          description: Task not found

  /api/tasks/{task_id}/tags:
    post:
      summary: Add tags to a task
      operationId: addTags
      tags: [Tasks]
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tags:
                  type: array
                  items:
                    type: string
              required: [tags]
      responses:
        '200':
          description: Tags added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

    delete:
      summary: Remove tags from a task
      operationId: removeTags
      tags: [Tasks]
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: tags
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Tags removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /api/audit:
    get:
      summary: Get audit log
      operationId: getAuditLog
      tags: [Audit]
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: query
          schema:
            type: string
            format: uuid
        - name: action
          in: query
          schema:
            type: string
            enum: [created, updated, completed, deleted]
        - name: from_date
          in: query
          schema:
            type: string
            format: date-time
        - name: to_date
          in: query
          schema:
            type: string
            format: date-time
        - name: limit
          in: query
          schema:
            type: integer
            default: 100
      responses:
        '200':
          description: Audit log entries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditListResponse'

  /health:
    get:
      summary: Health check
      operationId: healthCheck
      tags: [Health]
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  dapr_sidecar:
                    type: boolean

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatRequest:
      type: object
      properties:
        message:
          type: string
          description: Natural language command
          example: "Add task: Buy groceries with high priority, due tomorrow at 5pm"
      required: [message]

    ChatResponse:
      type: object
      properties:
        message:
          type: string
          description: Chatbot response
        action:
          type: string
          description: Action performed (create, update, complete, delete, list, search)
        task:
          $ref: '#/components/schemas/Task'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'

    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [pending, completed]
        priority:
          type: string
          enum: [High, Medium, Low]
        tags:
          type: array
          items:
            type: string
        due_at:
          type: string
          format: date-time
          nullable: true
        remind_at:
          type: string
          format: date-time
          nullable: true
        recurrence_pattern:
          type: string
          enum: [daily, weekly, monthly]
          nullable: true
        recurrence_end:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true

    TaskCreate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
        priority:
          type: string
          enum: [High, Medium, Low]
          default: Medium
        tags:
          type: array
          items:
            type: string
        due_at:
          type: string
          format: date-time
        remind_at:
          type: string
          format: date-time
        recurrence_pattern:
          type: string
          enum: [daily, weekly, monthly]
      required: [title]

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
        priority:
          type: string
          enum: [High, Medium, Low]
        tags:
          type: array
          items:
            type: string
        due_at:
          type: string
          format: date-time
        remind_at:
          type: string
          format: date-time
        recurrence_pattern:
          type: string
          enum: [daily, weekly, monthly]

    TaskListResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    AuditEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        task_id:
          type: string
          format: uuid
        user_id:
          type: string
        action:
          type: string
          enum: [created, updated, completed, deleted]
        changes:
          type: object
          additionalProperties: true
        timestamp:
          type: string
          format: date-time
        metadata:
          type: object
          additionalProperties: true

    AuditListResponse:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/AuditEntry'
        total:
          type: integer
