# T008 - Dapr Pub/Sub Component (Kafka)
# Phase V Todo Chatbot - Kafka via Redpanda
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "redpanda-0.redpanda.kafka.svc.cluster.local:9093"
    - name: consumerGroup
      value: "todo-chatbot"
    - name: authRequired
      value: "false"
    - name: maxMessageBytes
      value: "1048576"
    - name: consumeRetryInterval
      value: "100ms"
    - name: version
      value: "2.0.0"
scopes:
  - backend
  - notification
  - recurring
  - audit
  - websocket
