# T010 - Dapr Secrets Component (Kubernetes)
# Phase V Todo Chatbot - Kubernetes Secrets Store
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
